/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class FromStudentRecord extends javax.swing.JFrame {

    /**
     * Creates new form FromStudentRecord
     */
    public FromStudentRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAddres = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMathGrade = new javax.swing.JTextField();
        txtEnglishGrade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtScienceGrade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAverage = new javax.swing.JTextField();
        btnproses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 90, 20);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(150, 20, 160, 22);

        jLabel2.setText("Addres");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 90, 20);

        jLabel3.setText("Age");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 90, 20);
        getContentPane().add(txtAddres);
        txtAddres.setBounds(150, 50, 160, 22);

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        getContentPane().add(txtAge);
        txtAge.setBounds(150, 80, 160, 22);

        jLabel4.setText("mathGrade");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 110, 80, 20);

        jLabel5.setText("englishGrade");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 140, 69, 20);

        txtMathGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMathGradeActionPerformed(evt);
            }
        });
        getContentPane().add(txtMathGrade);
        txtMathGrade.setBounds(150, 110, 160, 22);

        txtEnglishGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnglishGradeActionPerformed(evt);
            }
        });
        getContentPane().add(txtEnglishGrade);
        txtEnglishGrade.setBounds(150, 140, 160, 22);

        jLabel6.setText("scienceGrade");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 170, 70, 20);

        txtScienceGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScienceGradeActionPerformed(evt);
            }
        });
        getContentPane().add(txtScienceGrade);
        txtScienceGrade.setBounds(150, 170, 160, 20);

        jLabel7.setText("average");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 230, 70, 20);
        getContentPane().add(txtAverage);
        txtAverage.setBounds(150, 230, 160, 22);

        btnproses.setText("PROSES");
        btnproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesActionPerformed(evt);
            }
        });
        getContentPane().add(btnproses);
        btnproses.setBounds(20, 200, 290, 23);

        setSize(new java.awt.Dimension(392, 283));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtMathGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMathGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMathGradeActionPerformed

    private void txtEnglishGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnglishGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnglishGradeActionPerformed

    private void txtScienceGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScienceGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScienceGradeActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesActionPerformed
        // TODO add your handling code here:
        dua_enam.StudentRecord student = new dua_enam.StudentRecord();
        student.setName(txtName.getText());
        student.setAddress(txtAddres.getText());
        student.setAGe(Integer.parseInt(txtAge.getText()));
        student.setMathGrade(Double.parseDouble(txtMathGrade.getText()));
        student.setEnglishGrade(Double.parseDouble(txtEnglishGrade.getText()));
        student.setScienceGrade(Double.parseDouble(txtScienceGrade.getText()));
        /////
        txtAverage.setText(student.getAverage()+"");
    }//GEN-LAST:event_btnprosesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromStudentRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnproses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAddres;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAverage;
    private javax.swing.JTextField txtEnglishGrade;
    private javax.swing.JTextField txtMathGrade;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtScienceGrade;
    // End of variables declaration//GEN-END:variables
}
