/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package latihanSoal;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class FromWarnet extends javax.swing.JFrame {

    /**
     * Creates new form FromWarnet
     */
    WarnetController controller;
    public FromWarnet() {
        initComponents();
        controller = new WarnetController(this);
        controller.tampil();
        controller.clearForm();
    }
    public JTable getTblWarnet() {
    return TblWarnet;
    }
    public JTextField getTxtKode() {
    return TxtKode;
    }
    public JTextField getTxtNama() {
    return TxtNama;
    }

    public JComboBox<String> getCmbJenis() {
        return CmbJenis;
    }

    public JTextField getTxtKeluar() {
        return TxtKeluar;
    }

    public JTextField getTxtMasuk() {
        return TxtMasuk;
    }

    public JTextField getTxtTanggal() {
        return TxtTanggal;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtKode = new javax.swing.JTextField();
        TxtNama = new javax.swing.JTextField();
        CmbJenis = new javax.swing.JComboBox<>();
        TxtTanggal = new javax.swing.JTextField();
        TxtMasuk = new javax.swing.JTextField();
        TxtKeluar = new javax.swing.JTextField();
        TxtTarif = new javax.swing.JTextField();
        BtnInsert = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblWarnet = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Kode");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 9, 27, 16);

        jLabel2.setText("Nama pelanggan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 43, 100, 16);

        jLabel3.setText("Jenis pelanggan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 68, 84, 16);

        jLabel4.setText("Tgl masuk");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(6, 96, 54, 16);

        jLabel5.setText("Jam masuk");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(6, 124, 59, 16);

        jLabel6.setText("Jam keluar");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(6, 152, 56, 16);

        jLabel7.setText("Tarif");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(6, 180, 23, 16);

        TxtKode.setText("jTextField1");
        getContentPane().add(TxtKode);
        TxtKode.setBounds(103, 6, 350, 22);

        TxtNama.setText("jTextField2");
        getContentPane().add(TxtNama);
        TxtNama.setBounds(103, 40, 350, 22);

        CmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(CmbJenis);
        CmbJenis.setBounds(103, 68, 350, 22);

        TxtTanggal.setText("jTextField3");
        getContentPane().add(TxtTanggal);
        TxtTanggal.setBounds(103, 96, 350, 22);

        TxtMasuk.setText("jTextField4");
        getContentPane().add(TxtMasuk);
        TxtMasuk.setBounds(103, 124, 350, 22);

        TxtKeluar.setText("jTextField5");
        getContentPane().add(TxtKeluar);
        TxtKeluar.setBounds(103, 152, 350, 22);
        getContentPane().add(TxtTarif);
        TxtTarif.setBounds(103, 180, 350, 22);

        BtnInsert.setText("Insert");
        BtnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(BtnInsert);
        BtnInsert.setBounds(10, 230, 72, 23);

        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUpdate);
        BtnUpdate.setBounds(110, 230, 72, 23);

        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDelete);
        BtnDelete.setBounds(210, 230, 72, 23);

        BtnCancel.setText("Cancel");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCancel);
        BtnCancel.setBounds(320, 230, 72, 23);

        TblWarnet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Pelanggan", "Jenis Pelanggan", "Tgl Masuk", "Jam Masuk", "Jam Keluar", "Tarif"
            }
        ));
        TblWarnet.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TblWarnetAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(TblWarnet);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 270, 452, 402);

        setSize(new java.awt.Dimension(553, 577));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
       controller.updateWarnet();
        controller.tampil();
        controller.clearForm();
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
       controller.deleteWarnet();
       controller.tampil();
       controller.clearForm();
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        controller.clearForm(); 
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void BtnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsertActionPerformed
        controller.saveWarnet();
        controller.tampil();
        controller.clearForm();
    }//GEN-LAST:event_BtnInsertActionPerformed

    private void TblWarnetAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TblWarnetAncestorAdded
        controller.getWarnet();
    }//GEN-LAST:event_TblWarnetAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromWarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromWarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromWarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromWarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromWarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromWarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromWarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromWarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromWarnet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnInsert;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JComboBox<String> CmbJenis;
    private javax.swing.JTable TblWarnet;
    private javax.swing.JTextField TxtKeluar;
    private javax.swing.JTextField TxtKode;
    private javax.swing.JTextField TxtMasuk;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtTanggal;
    private javax.swing.JTextField TxtTarif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

   
}
