/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rosi110624;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class FromPeminjaman extends javax.swing.JFrame {
    

    /**
     * Creates new form fromPeminjaman
     */
    PeminjamanController controller;
    public FromPeminjaman() {
        initComponents();
        controller = new PeminjamanController(this);
        controller.tampil();
        controller.clearForm();
    }

    public JTable getTblPeminjaman() {
        return TblPeminjaman;
    }

    public JTextField getTxtDenda() {
        return TxtDenda;
    }

    public JTextField getTxtKodeAnggota() {
        return TxtKodeAnggota;
    }

    public JTextField getTxtKodeBuku() {
        return TxtKodeBuku;
    }

    public JTextField getTxtTerlambat() {
        return TxtTerlambat;
    }

    public JTextField getTxtTglKembali() {
        return TxtTglKembali;
    }

    public JTextField getTxtTglPinjam() {
        return TxtTglPinjam;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtKodeAnggota = new javax.swing.JTextField();
        TxtKodeBuku = new javax.swing.JTextField();
        TxtTglPinjam = new javax.swing.JTextField();
        TxtTglKembali = new javax.swing.JTextField();
        TxtTerlambat = new javax.swing.JTextField();
        BtnInsert = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TxtDenda = new javax.swing.JTextField();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TxtTotal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblPeminjaman = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Kode Anggota");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 90, 16);

        jLabel2.setText("Kode Buku");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 40, 80, 16);

        jLabel3.setText("Tgl Pinjam");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 70, 80, 16);

        jLabel4.setText("Tgl Kembali");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 100, 80, 16);

        jLabel5.setText("Terlambat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 130, 70, 16);

        TxtKodeAnggota.setText("jTextField1");
        getContentPane().add(TxtKodeAnggota);
        TxtKodeAnggota.setBounds(140, 10, 470, 30);

        TxtKodeBuku.setText("jTextField2");
        getContentPane().add(TxtKodeBuku);
        TxtKodeBuku.setBounds(140, 40, 470, 30);

        TxtTglPinjam.setText("jTextField3");
        TxtTglPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTglPinjamActionPerformed(evt);
            }
        });
        getContentPane().add(TxtTglPinjam);
        TxtTglPinjam.setBounds(140, 70, 470, 30);

        TxtTglKembali.setText("jTextField4");
        getContentPane().add(TxtTglKembali);
        TxtTglKembali.setBounds(140, 100, 470, 30);

        TxtTerlambat.setText("jTextField5");
        getContentPane().add(TxtTerlambat);
        TxtTerlambat.setBounds(140, 130, 470, 30);

        BtnInsert.setText("Insert");
        BtnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(BtnInsert);
        BtnInsert.setBounds(140, 210, 80, 30);

        jLabel6.setText("Denda");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 160, 34, 16);

        TxtDenda.setText("jTextField6");
        getContentPane().add(TxtDenda);
        TxtDenda.setBounds(140, 160, 470, 30);

        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUpdate);
        BtnUpdate.setBounds(262, 203, 80, 40);

        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDelete);
        BtnDelete.setBounds(392, 203, 80, 40);

        BtnCancel.setText("Cancel");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCancel);
        BtnCancel.setBounds(520, 200, 90, 40);

        jLabel7.setText("Total");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 270, 26, 16);
        getContentPane().add(TxtTotal);
        TxtTotal.setBounds(140, 260, 470, 40);

        TblPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Anggota", "Kode Buku", "Tgl Pinjam", "Tgl Kembali", "Terlambat", "Denda", "Total"
            }
        ));
        TblPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblPeminjamanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TblPeminjaman);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 320, 610, 402);

        setSize(new java.awt.Dimension(644, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void TxtTglPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTglPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTglPinjamActionPerformed

    private void BtnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsertActionPerformed
       controller.calculateTerlambatAndDenda();
       controller.savePinjam();
       controller.tampil();
       controller.clearForm();
    }//GEN-LAST:event_BtnInsertActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        controller.calculateTerlambatAndDenda();
       controller.updatePinjam();
       controller.tampil();
       controller.clearForm();
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
     controller.deletePinjam();
       controller.tampil();
       controller.clearForm();
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
       controller.clearForm();
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void TblPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblPeminjamanMouseClicked
        controller.getPinjam();
    }//GEN-LAST:event_TblPeminjamanMouseClicked

     private void calculateTerlambatAndDenda() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date tanggalPinjam = sdf.parse(TxtTglPinjam.getText());
            Date tanggalKembali = sdf.parse(TxtTglKembali.getText());

            long differenceInMillies = Math.abs(tanggalKembali.getTime() - tanggalPinjam.getTime());
            long differenceInDays = differenceInMillies / (24 * 60 * 60 * 1000);

            TxtTerlambat.setText(String.valueOf(differenceInDays));
            TxtDenda.setText(String.valueOf(differenceInDays * 500));
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromPeminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnInsert;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTable TblPeminjaman;
    private javax.swing.JTextField TxtDenda;
    private javax.swing.JTextField TxtKodeAnggota;
    private javax.swing.JTextField TxtKodeBuku;
    private javax.swing.JTextField TxtTerlambat;
    private javax.swing.JTextField TxtTglKembali;
    private javax.swing.JTextField TxtTglPinjam;
    private javax.swing.JTextField TxtTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

   
      
}
